package org.aksw.sessa.query.models;

/**
 * This class is used to store a candidate for a n-gram and its energy.
 * The energy approximates the probability that a node should be part of or lead to the solution generated by SESSA.
 */
public class Candidate {

  private String candidateString;
  private float energy;

  /**
   * Constructs a Candidate with its content.
   * More formally it contains the URI that was found for a n-gram and its energy.
   * @param candidateString URI found for a n-gram that is used as candidate
   * @param energy energy value to the found string
   */
  public Candidate(String candidateString, float energy){
    this.candidateString = candidateString;
    this.energy = energy;
  }

  /**
   * Returns the URI for this candidate.
   * @return the URI for this candidate
   */
  public String candidateString() {
    return candidateString;
  }

  /**
   * Returns the energy of this candidate.
   * @return the energy of this candidate
   */
  public float getEnergy() {
    return energy;
  }
}
