package org.aksw.sessa.importing.dictionary.energy;

/**
 * This interface is used for implementations of the energy function. The energy function
 * approximates the probability that a node should be part of or lead to the solution generated by
 * SESSA.
 */
public interface EnergyFunctionInterface {

  /**
   * Returns the energy score of an URI with the given data. As the energy score can be calculated
   * in various ways, all needed parameters are given to the method.
   *
   * @param nGram original n-gram with which the uri was found
   * @param foundURI found URI for which the energy score should be calculated
   * @param foundKey key of the dictionary for which the URI is the value
   * @return the energy score of an URI with the given data
   */
  float calculateEnergyScore(String nGram, String foundURI, String foundKey);

}
